services:
  postgres:
    image: postgres:18-alpine
    container_name: 4sports_pg_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 4sports

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
